<?php
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class AudiateAdmin {
    private $audiate_options;

    public function __construct() {
        add_action( 'admin_menu', array( $this, 'audiate_add_plugin_page' ) );
        add_action( 'admin_init', array( $this, 'audiate_page_init' ) );
    }

    public function audiate_add_plugin_page() {
        add_options_page('Audiate', // page_title
            'Audiate', // menu_title
            'manage_options', // capability
            'audiate', // menu_slug
            array( $this, 'audiate_create_admin_page' ) // function
        );
    }

    public function audiate_create_admin_page() {
        $this->audiate_options = get_option( 'audiate_option_name' ); ?>

        <div class="wrap">
            <h2>Audiate</h2>
            <p>Sign up for a free account at <a href="https://audiate.me" target="_blank">Audiate.me</a>. Create a widget and copy the code to this page.</p>
            <?php settings_errors(); ?>

            <form method="post" action="options.php">
                <?php
                settings_fields( 'audiate_option_group' );
                do_settings_sections( 'audiate-admin' );
                submit_button();
                ?>
            </form>
        </div>
    <?php }

    public function audiate_page_init() {
        register_setting(
            'audiate_option_group', // option_group
            'audiate_option_name', // option_name
            array( $this, 'audiate_sanitize' ) // sanitize_callback
        );

        add_settings_section(
            'audiate_setting_section', // id
            'Settings', // title
            array( $this, 'audiate_section_info' ), // callback
            'audiate-admin' // page
        );


        add_settings_field(
            'widget_code_2', // id
            'Widget Code', // title
            array( $this, 'widget_code_2_callback' ), // callback
            'audiate-admin', // page
            'audiate_setting_section' // section
        );

        add_settings_field(
            'show_on_all_posts_1', // id
            'Show on all posts', // title
            array( $this, 'show_on_all_posts_1_callback' ), // callback
            'audiate-admin', // page
            'audiate_setting_section' // section
        );

        add_settings_field(
            'show_on_all_pages_3', // id
            'Show on all pages', // title
            array( $this, 'show_on_all_pages_3_callback' ), // callback
            'audiate-admin', // page
            'audiate_setting_section' // section
        );

        add_settings_field(
            'position_4', // id
            'Widget Placement', // title
            array( $this, 'position_4_callback' ), // callback
            'audiate-admin', // page
            'audiate_setting_section' // section
        );

    }

    public function audiate_sanitize($input) {
        $sanitary_values = array();

        if ( isset( $input['show_on_all_posts_1'] ) ) {
            $sanitary_values['show_on_all_posts_1'] = sanitize_text_field($input['show_on_all_posts_1']);
        }

        if ( isset( $input['widget_code_2'] ) ) {
            $sanitary_values['widget_code_2'] =  $input['widget_code_2'] ;
        }


        if ( isset( $input['show_on_all_pages_3'] ) ) {
            $sanitary_values['show_on_all_pages_3'] = sanitize_text_field($input['show_on_all_pages_3']);
        }

        if ( isset( $input['position_4'] ) ) {
            $sanitary_values['position_4'] = sanitize_text_field($input['position_4']);
        }

        return $sanitary_values;
    }

    public function audiate_section_info() {

    }

    public function show_on_all_posts_1_callback() {
        ?> <select name="audiate_option_name[show_on_all_posts_1]" id="show_on_all_posts_1">
            <?php $selected = (isset( $this->audiate_options['show_on_all_posts_1'] ) && $this->audiate_options['show_on_all_posts_1'] === 'yes') ? 'selected' : '' ; ?>
            <option value="yes" <?php echo $selected; ?>>Yes</option>
            <?php $selected = (isset( $this->audiate_options['show_on_all_posts_1'] ) && $this->audiate_options['show_on_all_posts_1'] === 'no') ? 'selected' : '' ; ?>
            <option value="no" <?php echo $selected; ?>>Only when selected</option>
        </select> <?php
    }

    public function show_on_all_pages_3_callback() {
        ?> <select name="audiate_option_name[show_on_all_pages_3]" id="show_on_all_pages_3">
            <?php $selected = (isset( $this->audiate_options['show_on_all_pages_3'] ) && $this->audiate_options['show_on_all_pages_3'] === 'yes') ? 'selected' : '' ; ?>
            <option value="yes" <?php echo $selected; ?>>Yes</option>
            <?php $selected = (isset( $this->audiate_options['show_on_all_pages_3'] ) && $this->audiate_options['show_on_all_pages_3'] === 'no') ? 'selected' : '' ; ?>
            <option value="no" <?php echo $selected; ?>>Only when selected</option>
        </select> <?php
    }

    public function position_4_callback() {
        ?> <select name="audiate_option_name[position_4]" id="position_4">
            <?php $selected = (isset( $this->audiate_options['position_4'] ) && $this->audiate_options['position_4'] === 'before_content') ? 'selected' : '' ; ?>
            <option value="before_content" <?php echo $selected; ?>>Before Content</option>
            <?php $selected = (isset( $this->audiate_options['position_4'] ) && $this->audiate_options['position_4'] === 'after_title') ? 'selected' : '' ; ?>
            <option value="after_title" <?php echo $selected; ?>>After Title</option>
        </select> <?php
    }

    public function widget_code_2_callback() {
        printf(
            '<textarea class="regular-text" rows="5" name="audiate_option_name[widget_code_2]" id="widget_code_2">%s</textarea>',
            isset( $this->audiate_options['widget_code_2'] ) ? esc_attr( $this->audiate_options['widget_code_2']) : ''
        );
    }
}
if ( is_admin() )
	$audiate = new AudiateAdmin();

/* 
 * Retrieve this value with:
 * $audiate_options = get_option( 'audiate_option_name' ); // Array of All Options
 * $widget_id_0 = $audiate_options['widget_id_0']; // Widget id
 * $show_on_all_posts_1 = $audiate_options['show_on_all_posts_1']; // Show on all posts
 */
